### ISSUE TITLE
mzn-bench check-solutions not working correctly?

### ISSUE THREAD

**Issue by ptal** [Dekker1/minizinc-slurm#31]
Hi,

I was trying to check the solutions given by my solver, Gecode and OrTools. Surprisingly, the program says that Gecode and OrTools give wrong answers on a model from the MiniZinc competition 2022:

```
FAILED results2/1_Gecode_sol.yml::Gecode:ma-path-finding:../../mzn-challenge/2022/ma-path-finding/mapf.mzn:../../mzn-challenge/2022/ma-path-finding/ins_g32_p20_a10.dzn:31 - AssertionError: Incorrect solution
FAILED results2/1_OrTools_sol.yml::OrTools:ma-path-finding:../../mzn-challenge/2022/ma-path-finding/mapf.mzn:../../mzn-challenge/2022/ma-path-finding/ins_g32_p20_a10.dzn:29 - AssertionError: Incorrect solution
```

I think it is safe to assume they cannot be both wrong.

Maybe you can try to replicate it and confirm the issue.
Files:
* [instances2.csv](https://github.com/MiniZinc/mzn-bench/files/12727899/instances2.csv)
* `test2.py`:
```python
from datetime import timedelta
from pathlib import Path

import minizinc

from mzn_bench import Configuration, schedule

schedule(
    instances=Path("instances2.csv"),
    output_dir=Path.cwd() / "results2",
    timeout=timedelta(seconds=305),
    configurations=[
        Configuration(name="OrTools", solver=minizinc.Solver.lookup("ortools")),
        Configuration(name="Gecode", solver=minizinc.Solver.lookup("gecode"))
    ],
    nodelist=None
)
```

**Comment by Dekker1** [comment]
@hbierlee Do you have some time to look at this?

**Comment by hbierlee** [comment]
Sure!

@ptal , could you share the yml result files as well? Otherwise I can try to rerun the model myself (but then it could turn out that I get a different solution that doesn't have the issue; if so, it would help to know the solver versions as well). Also, I assume the model and data file are unchanged from the downloads from the MiniZinc competition?

Cheers,

Henk

**Comment by ptal** [comment]
Here are the [yml.zip](https://github.com/MiniZinc/mzn-bench/files/12747097/results2.zip).
Yes, it's the files from the mzn-challenge repository.
Thanks!

**Comment by hbierlee** [comment]
Hi @ptal ,

The problem is that the solution checker runs out of its allotted 5 second of "solving" (checking) time, since the instance for mapf is quite large. I'm working on a PR for `minizinc-python` so that `check_solution` raises an error instead returning `False` (which wrongly implies the solution is incorrect), and adding a way to increase/remove the timeout in `mzn-bench`.

In the meantime, you could remove the timeout yourself by removing the timeout argument in `helpers.py` in `check = instance.solve(timeout=timedelta(seconds=5))`. If you haven't already, you can clone `minizinc-python` and set it as develop dependency in `pyproject.toml` to make that change in the source code:

```
# minizinc = "^0.9"
minizinc = {path = "../minizinc-python", develop = true}
```

Cheers,

Henk

**Comment by ptal** [comment]
Thank you for looking into it!
